import numpy as np
import pandas as pd

def period_from_hour(s):
    return pd.cut(s, bins=[-1,5,11,17,21,24], labels=["night","morning","afternoon","evening","late_night"])

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    X = df.copy()
    for c in ["insert_date","start_date","end_date"]:
        X[c] = pd.to_datetime(X[c], errors="coerce")

    # Core time features
    X["departure_hour"] = X["start_date"].dt.hour
    X["arrival_hour"] = X["end_date"].dt.hour
    X["departure_weekday"] = X["start_date"].dt.dayofweek
    X["arrival_weekday"] = X["end_date"].dt.dayofweek
    X["departure_month"] = X["start_date"].dt.month
    X["departure_dayofyear"] = X["start_date"].dt.dayofyear
    X["is_weekend"] = X["departure_weekday"].isin([5,6]).astype(int)

    X["departure_period"] = period_from_hour(X["departure_hour"])
    X["arrival_period"] = period_from_hour(X["arrival_hour"])

    X["season"] = X["departure_month"].map({
        12:"winter",1:"winter",2:"winter",
        3:"spring",4:"spring",5:"spring",
        6:"summer",7:"summer",8:"summer",
        9:"autumn",10:"autumn",11:"autumn"
    })

    # Journey duration, correctly allowing overnight journeys
    X["journey_duration_hours"] = (
        X["end_date"] - X["start_date"]
    ).dt.total_seconds() / 3600

    # Booking lead time
    X["advance_booking_hours"] = (
        X["start_date"] - X["insert_date"]
    ).dt.total_seconds() / 3600

    X["is_overnight"] = (X["end_date"].dt.date != X["start_date"].dt.date).astype(int)
    X["same_day_journey"] = (X["is_overnight"] == 0).astype(int)

    # Route/category features
    X["origin"] = X["origin"].fillna("UNKNOWN").astype(str).str.strip().str.upper()
    X["destination"] = X["destination"].fillna("UNKNOWN").astype(str).str.strip().str.upper()
    X["train_type"] = X["train_type"].fillna("UNKNOWN").astype(str)
    X["train_class"] = X["train_class"].fillna("UNKNOWN").astype(str)
    X["fare"] = X["fare"].fillna("UNKNOWN").astype(str)

    X["route_key"] = X["origin"] + "__" + X["destination"]
    X["route_frequency"] = X.groupby("route_key")["route_key"].transform("count")
    X["origin_frequency"] = X.groupby("origin")["origin"].transform("count")
    X["destination_frequency"] = X.groupby("destination")["destination"].transform("count")

    # A frequency-based proxy for route complexity/cardinality
    X["route_length_proxy"] = X["origin_frequency"] + X["destination_frequency"]

    X["train_class_x_train_type"] = X["train_class"] + "__" + X["train_type"]
    X["route_x_train_type"] = X["route_key"] + "__" + X["train_type"]

    # Clean impossible values generated by bad timestamps
    for c in ["journey_duration_hours","advance_booking_hours"]:
        X[c] = X[c].replace([np.inf, -np.inf], np.nan)

    # We don't feed raw timestamps directly to the model.
    drop_cols = ["price","Unnamed: 0","insert_date","start_date","end_date","route_key"]
    return X.drop(columns=[c for c in drop_cols if c in X.columns], errors="ignore")

def feature_names():
    return [
        "origin","destination","train_type","train_class","fare",
        "departure_hour","arrival_hour","departure_weekday","arrival_weekday",
        "departure_month","departure_dayofyear","is_weekend",
        "departure_period","arrival_period","season",
        "journey_duration_hours","advance_booking_hours","is_overnight",
        "same_day_journey","route_frequency","origin_frequency",
        "destination_frequency","route_length_proxy",
        "train_class_x_train_type","route_x_train_type"
    ]
